# Generated by Django 6.0 on 2025-12-13 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', '進行中'), ('paused', '中断'), ('completed', '完了')], default='active', max_length=20, verbose_name='ステータス')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='開始日時')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('current_question_index', models.IntegerField(default=0, verbose_name='現在の問題番号')),
            ],
            options={
                'verbose_name': 'クイズセッション',
                'verbose_name_plural': 'クイズセッション一覧',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='VitalPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='番号')),
                ('name', models.CharField(max_length=50, verbose_name='急所名')),
                ('reading', models.CharField(max_length=50, verbose_name='読み仮名')),
                ('category', models.CharField(max_length=100, verbose_name='カテゴリ')),
                ('image_file', models.CharField(max_length=255, verbose_name='画像ファイル名')),
            ],
            options={
                'verbose_name': '急所',
                'verbose_name_plural': '急所一覧',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LearningHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_count', models.IntegerField(default=0, verbose_name='正解回数')),
                ('incorrect_count', models.IntegerField(default=0, verbose_name='不正解回数')),
                ('last_learned_at', models.DateTimeField(blank=True, null=True, verbose_name='最終学習日時')),
                ('vital_point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='quiz.vitalpoint', verbose_name='急所')),
            ],
            options={
                'verbose_name': '学習履歴',
                'verbose_name_plural': '学習履歴一覧',
            },
        ),
        migrations.CreateModel(
            name='SessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_order', models.IntegerField(verbose_name='出題順')),
                ('is_answered', models.BooleanField(default=False, verbose_name='回答済み')),
                ('is_correct', models.BooleanField(default=False, verbose_name='正解')),
                ('attempt_count', models.IntegerField(default=0, verbose_name='試行回数')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quizsession', verbose_name='セッション')),
                ('vital_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.vitalpoint', verbose_name='急所')),
            ],
            options={
                'verbose_name': 'セッション問題',
                'verbose_name_plural': 'セッション問題一覧',
                'ordering': ['question_order'],
                'unique_together': {('session', 'question_order')},
            },
        ),
    ]
