# Generated by Django 6.0 on 2025-12-14 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='mode',
            field=models.CharField(choices=[('test', 'テスト'), ('review', '復習')], default='test', max_length=20, verbose_name='モード'),
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='完了日時')),
                ('total_questions', models.IntegerField(verbose_name='総問題数')),
                ('correct_count', models.IntegerField(verbose_name='正解数')),
                ('incorrect_count', models.IntegerField(verbose_name='不正解数')),
                ('score', models.IntegerField(verbose_name='得点')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_result', to='quiz.quizsession', verbose_name='セッション')),
            ],
            options={
                'verbose_name': 'テスト結果',
                'verbose_name_plural': 'テスト結果一覧',
                'ordering': ['-completed_at'],
            },
        ),
    ]
